### ISSUE TITLE
Correct the `%recipient%` when replying to own email 

### ISSUE THREAD

**Issue by stephankoenig** [RealRaven2000/SmartTemplates#239] opened 2023-04-27 15:13 UTC
When I hit reply on an email I have written before (in the sent folder), Thunderbird does not respond to me, but changes out the recipient and sends an email to the (old) recipient with me as the sender.

SmartTemplate, however, uses %recipient(firstname)% addresses me, the sender. 

I have to manually switch to a different template that uses %to(firstname)%.

Is there any way to avoid that manual step?

**Comment by stephankoenig** [comment] 2023-04-27 21:38
If worse comes to worst, is it not possible to copy the routine from Thunderbird that detects this specific case and switches out the sender and recipient, so Smarttemplate does the same?

**Comment by RealRaven2000** [comment] 2023-04-27 21:42
> If worse comes to worst, is it not possible to copy the routine from Thunderbird that detects this specific case and switches out the sender and recipient, so Smarttemplate does the same?

We will see - there is a listener for somebody changing the "from" address manually - but this normally triggers the template of the account identity (not the external HTML ones) - and I may have disabled it because it wouldn't be wanted to lose an external template just because one switches the identity in composer. But it is also possible that Thunderbird goes a completely different way here and never triggers the event - I will have to investigate it in detail.

**Comment by KlausEyl** [comment] 2023-08-21 18:59
I am not sure if this is what I need, but when I "answer" my own email to send a reminder, Thunderbird works correctly, but SmartTemplate does not. So it would be great if this could be fixed.

**Comment by RealRaven2000** [comment] 2023-08-21 19:19
Thanks, it's not trivial to fix but it definitely should be. I will pin it to the most favorite 3 issues so I can work on this one next.

**Comment by KlausEyl** [comment] 2023-08-25 16:15
Thank you! This will make SmartTemplate so much more useful for me!

**Comment by RealRaven2000** [comment] 2023-08-25 19:44
Now that the issue is pinned, I just need to make time for it. This and the hiding of irrelevant reply-all / reply-to-list will be high priority for the next version for Thunderbird 115. If nothing happens in this area within 4 weeks, please ping me here again, and make sure I sort it out!!

**Comment by KlausEyl** [comment] 2023-09-26 21:44
Hi! I'm not trying to nudge, but do you know if it can be done? So is it just a question of time, or not sure that it will work?

**Comment by RealRaven2000** [comment] 2024-01-19 15:54
I am just testing here with the latest version, but at least here in Thunderbird 115 it seems resolved.
Can you test with the version below?

[smartTemplate-fx-4.4pre13.zip](https://github.com/RealRaven2000/SmartTemplates/files/13991350/smartTemplate-fx-4.4pre13.zip)

**Comment by RealRaven2000** [comment] 2024-02-19 15:51
I made a version after revisiting this. I had problems with recipient when using a smart fragment from the menu in composer, see

https://github.com/RealRaven2000/SmartTemplates/issues/246#issuecomment-1952745446

Please test this version:

[smartTemplate-fx-4.4pre17.zip](https://github.com/RealRaven2000/SmartTemplates/files/14334345/smartTemplate-fx-4.4pre17.zip)

---

To test the version above, download the zip file and drag the file into Thunderbird Add-ons Manager without extracting contents.

**Comment by RealRaven2000** [comment] 2024-03-29 11:41
Fixed in 4.4 - published 28/03/2024

**Closed by RealRaven2000** 2024-03-29 11:41 UTC
Labels: bug
