### ISSUE TITLE
Reply mode instable bug: instantiation of template is duplicated

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/SmartTemplates#132] opened 2021-05-08 17:20 UTC
**SmartTemplate⁴ 4.4 Pro** & **QuickFolders 5.5.2 Pro** running

What is the meaning of this message?
_Console error message:_

![floating-screenshot-190310](https://user-images.githubusercontent.com/26068595/117547553-769f4400-b030-11eb-833d-a7c9a9a1d174.jpg)

_Quote Header_

```
On %X:=sent%%dateformat(d/m/Y H:M:S)% %from(name,bracketMail())% wrote:
> To: %to(name)% <%to(mail)%>[[
> Cc: %cc(name)% <%cc(mail)%>]]
> Subject: %subject%
> Message-ID: %Message-ID%
[[> Reply-to: %Reply-to%
]]>
```

_Template:_

```
%cursor%
%header.set(priority,high)%
%sig(text)%
```
You are welcome if more infos are needed.

**Comment by RealRaven2000** [comment] 2021-05-08 20:51
It's kind of an old error - but I think I have a fix for it now. I am replacing the generic function for the composer stateListener `NotifyComposeBodyReady()` with a specific version for SmartTemplates. Once SmartTemplates has done it's own processing, Thunderbird's orginal function is called. Thundebird internally uses the keyword `this` to reference into another function 
`NotifyComposeBodyReadyReply` and fails - I have changed the way I store the original fallback notification by "binding" it to the original object:

```
   util.OrigNotify = 
            (gComposeType == msgComposeType.New)
            ? stateListener.NotifyComposeBodyReadyNew.bind(stateListener)
            : stateListener.NotifyComposeBodyReady.bind(stateListener);
```
            
Test Version here:

[smartTemplate-fx-3.5pre95.zip](https://github.com/RealRaven2000/SmartTemplate4/files/6446549/smartTemplate-fx-3.5pre95.zip)

Apart from not having the error message, does this behave any differently when you reply with a template?

**Comment by macdeport** [comment] 2021-05-09 10:00
1. I can confirm the SmartTemplate⁴ error message has disappeared.

But this one still exists, what is its meaning?
![floating-screenshot-115150](https://user-images.githubusercontent.com/26068595/117567630-2b7f4280-b0bd-11eb-8075-51cfb7f7fba4.jpg)

2. When QF is running (my use case of course ;-) ) instantiation of template is sadly duplicated although this behavior sometimes exists before this current fix...

**Comment by RealRaven2000** [comment] 2021-05-09 12:28
> But this one still exists, what is its meaning?

I don't know, but don't think it is relevant

> When QF is running (my use case of course ;-) ) instantiation of template is sadly duplicated although this behavior sometimes exists before this current fix...

What is QuickFolders doing in this case? Are you setting from / to address via advanced tab properties? You can export your template from SmartTemplates so I can test. If it happens every time this is helpful because it makes it reproducible for me

**Comment by macdeport** [comment] 2021-05-09 15:28
> What is QuickFolders doing in this case? Are you setting from / to address via advanced tab properties?

Yes exactly: one of the useful features of QF.

> You can export your template from SmartTemplates so I can test.

[smarttemplate-al@xxx.yy.json.zip](https://github.com/RealRaven2000/SmartTemplate4/files/6447791/smarttemplate-al%40xxx.yy.json.zip)

Seems to occur every time _when only and only if_ the account forced by  QF is the TB default account...

**Comment by macdeport** [comment] 2021-05-14 09:09
This annoying duplication has reappeared outside the previous case...

It is reproducible until the use of the workaround which removes the effect of this instability (bug) temporarily.

Bypass until next time: stop / restart ST.

**Comment by RealRaven2000** [comment] 2021-09-18 12:36
Please also reference https://github.com/RealRaven2000/SmartTemplates/issues/139 I am doing some work over there.

**Comment by RealRaven2000** [comment] 2022-01-20 18:49
Since #139 is closed I assume this duplication issue also resolved. Closing for now unless you experience it again, in which case you can reopen it

**Closed by RealRaven2000** 2022-01-20 18:49 UTC

**Comment by RealRaven2000** [comment] 2022-02-01 13:52
Does this still happen with the current version? Otherwise I would close the issue

**Comment by macdeport** [comment] 2022-02-01 18:02
I am now running version 3.10pre13 on Thunderbird 78.14.0: _zen_ filling at till now...
